name: Simple workflow on pull-request

on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  helloWorld:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: first test
      run: ls -l

    - name: second test
      run: ls -l ./bin/

    - name: third test
      run: ./bin/ubuntu/aggregate
