name: Simple workflow on pull-request

on:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  helloWorld:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
    - name: first test
      run: ls -l
    - name: second test
      working-directory: /home/runner/work/git-analytics-actions
      run: ls -l
    - name: third test
      working-directory: /home/runner/work/git-analytics-actions/git-analytics-actions
      run: ls -l